---
- name: Install developer productivity command line packages
  yum:
    name:
      - man
      - vim
      - ctags # For vim
      - mc
      - screen
      - diffutils # for diffing large results in conquest tests
    state: present
    use_backend: yum
  become: true
