---
  - name: Install developer productivity command line packages
    yum: 
      name:
        - man
        - vim
        - ctags # For vim
        - mc
        - screen
        - diffutils # for diffing large results in conquest tests
      state: latest
      use_backend: yum
    become: yes

  - name: install RBTools via pip
    pip:
      name: RBTools
      state: latest
      executable: pip3
      extra_args: '--user'
