---
- name: Install developer productivity command line packages
  apt:
    name:
      - man
      - vim
      - ctags # For vim
      - mc
      - screen
      - diffutils # for diffing large results in conquest tests
    state: present
  become: true
